# GitHub Copilot setup steps for the Storybook MCP repository
# This file defines the steps to prepare the repository environment for AI development
# See: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

name: Setup Storybook MCP Development Environment

steps:
  - name: Setup Node.js and Install Dependencies
    uses: ./.github/actions/setup-node-and-install

  - name: Build packages
    run: |
      # Build all packages in the monorepo
      # This is required before running tests, linting, or typechecking
      pnpm turbo run build
