packages:
  - packages/*
  - apps/*
  - eval/
  - eval/template/project
  - eval/evals/*/experiments/*/project

catalog:
  storybook: 10.1.0-alpha.10
  '@storybook/addon-a11y': 10.1.0-alpha.10
  '@storybook/addon-docs': 10.1.0-alpha.10
  '@storybook/addon-vitest': 10.1.0-alpha.10
  '@storybook/react-vite': 10.1.0-alpha.10
  eslint-plugin-storybook: 10.1.0-alpha.10

  tmcp: ^1.16.0
  '@tmcp/adapter-valibot': ^0.1.4
  '@tmcp/transport-http': ^0.8.0
  '@tmcp/transport-stdio': ^0.4.1

  valibot: ^1.1.0
  vite: ^7.2.2

# these are the versions used for all the eval experiments.
# ensuring they use the exact same versions greatly speeds up dependency installation because they can be locally cached
catalogs:
  experiments:
    storybook: 10.1.0-alpha.10
    '@storybook/addon-docs': 10.1.0-alpha.10
    '@storybook/addon-a11y': 10.1.0-alpha.10
    '@storybook/addon-vitest': 10.1.0-alpha.10
    '@storybook/react-vite': 10.1.0-alpha.10
    'eslint-plugin-storybook': 10.1.0-alpha.10

    react: 19.2.0
    'react-dom': 19.2.0
    '@types/react': 19.2.6
    '@types/react-dom': 19.2.6

    eslint: 9.39.1
    '@eslint/js': 9.39.1
    'eslint-plugin-react-hooks': 7.0.1
    'eslint-plugin-react-refresh': 0.4.24
    'typescript-eslint': 8.47.0

    typescript: 5.9.3
    '@types/node': 24.10.1

    vite: 7.2.2
    '@vitejs/plugin-react-swc': 4.2.2
    globals: 16.5.0

    vitest: 4.0.10
    '@vitest/browser-playwright': 4.0.10

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
