packages:
  - packages/*
  - apps/*

catalog:
  '@storybook/addon-docs': 10.1.0-alpha.9
  '@storybook/react-vite': 10.1.0-alpha.9
  '@tmcp/adapter-valibot': ^0.1.4
  '@tmcp/transport-http': ^0.8.0
  storybook: 10.1.0-alpha.9
  tmcp: ^1.16.0
  valibot: ^1.1.0

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
