packages:
  - packages/*
  - apps/*
  - eval
  - '!eval/templates/project'
  - '!eval/tasks/*/trials/*/project'

catalog:
  '@storybook/addon-a11y': 10.3.0-alpha.4
  '@storybook/addon-docs': 10.3.0-alpha.4
  '@storybook/addon-vitest': 10.3.0-alpha.4
  '@storybook/react-vite': 10.3.0-alpha.4
  '@tmcp/adapter-valibot': ^0.1.4
  '@tmcp/transport-http': ^0.8.0
  '@tmcp/transport-stdio': ^0.4.1
  eslint-plugin-storybook: 10.3.0-alpha.4
  storybook: 10.3.0-alpha.4
  tmcp: ^1.16.0
  tsdown: ^0.15.12
  typescript: ^5.9.3
  valibot: 1.2.0
  vite: 7.2.2
  vitest: 4.0.6

catalogs:
  trials:
    '@eslint/js': 9.39.1
    '@storybook/addon-a11y': 10.3.0-alpha.4
    '@storybook/addon-docs': 10.3.0-alpha.4
    '@storybook/addon-vitest': 10.3.0-alpha.4
    '@storybook/react-vite': 10.3.0-alpha.4
    '@types/node': 24.10.1
    '@types/react': 19.2.6
    '@types/react-dom': 19.2.3
    '@vitejs/plugin-react-swc': 4.2.2
    '@vitest/browser-playwright': 4.0.6
    eslint: 9.39.1
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.4.24
    eslint-plugin-storybook: 10.3.0-alpha.4
    globals: 16.5.0
    react: 19.2.0
    react-dom: 19.2.0
    storybook: 10.3.0-alpha.4
    typescript: 5.9.3
    typescript-eslint: 8.47.0
    vite: 7.2.2
    vitest: 4.0.6

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
