packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - esbuild

catalog:
  tmcp: ^1.15.2
  '@tmcp/adapter-valibot': ^0.1.4
  '@tmcp/transport-http': ^0.7.0
  valibot: ^1.1.0
  tsdown: ^0.15.9
  typescript: ^5.9.3
  vitest: ^3.2.4
  '@vitest/coverage-v8': 3.2.4
  '@types/node': 20.19.0
  'storybook': 0.0.0-pr-32816-sha-28f59f53
  '@storybook/addon-docs': 0.0.0-pr-32816-sha-28f59f53
  '@storybook/react-vite': 0.0.0-pr-32816-sha-28f59f53
