packages:
  - packages/*
  - apps/*

catalog:
  '@storybook/addon-docs': 0.0.0-pr-32810-sha-6e759c7e
  '@storybook/react-vite': 0.0.0-pr-32810-sha-6e759c7e
  '@tmcp/adapter-valibot': ^0.1.4
  '@tmcp/transport-http': ^0.8.0
  '@types/node': 20.19.0
  '@vitest/coverage-v8': 3.2.4
  storybook: 0.0.0-pr-32810-sha-6e759c7e
  tmcp: ^1.16.0
  tsdown: ^0.15.9
  typescript: ^5.9.3
  valibot: ^1.1.0
  vitest: 3.2.4
  publint: 0.3.15

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
