packages:
  - packages/*
  - apps/*
  - eval/
  - eval/template/project
  - eval/evals/*/experiments/*/project

catalog:
  '@storybook/addon-a11y': 10.1.0-alpha.8
  '@storybook/addon-docs': 10.1.0-alpha.8
  '@storybook/addon-vitest': 10.1.0-alpha.8
  '@storybook/react-vite': 10.1.0-alpha.8
  '@tmcp/adapter-valibot': ^0.1.4
  '@tmcp/transport-http': ^0.8.0
  '@tmcp/transport-stdio': ^0.4.1
  '@types/node': 24.10.0
  '@vitest/browser-playwright': 4.0.6
  '@vitest/coverage-v8': 4.0.6
  eslint-plugin-storybook: 10.1.0-alpha.8
  publint: 0.3.15
  storybook: 10.1.0-alpha.8
  tmcp: ^1.16.0
  tsdown: ^0.15.12
  typescript: ^5.9.3
  valibot: 1.1.0
  vitest: 4.0.6

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
