packages:
  - packages/*
  - apps/*
  - eval/
  - eval/template/project
  - eval/evals/*/experiments/*/project

catalog:
  '@storybook/addon-a11y': 10.1.0-alpha.10
  '@storybook/addon-docs': 10.1.0-alpha.10
  '@storybook/addon-vitest': 10.1.0-alpha.10
  '@storybook/react-vite': 10.1.0-alpha.10
  '@tmcp/adapter-valibot': ^0.1.4
  '@tmcp/transport-http': ^0.8.0
  '@tmcp/transport-stdio': ^0.4.1
  storybook: 10.1.0-alpha.10
  eslint-plugin-storybook: 10.1.0-alpha.10
  tmcp: ^1.16.0
  valibot: ^1.1.0
  vite: ^7.2.2

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
