name: 'Setup Node.js and Dependencies'
description: 'Sets up Node.js, caches, installs dependencies and turbo cache'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
    - name: Use Node.js 24
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: '.nvmrc'
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install
    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@v2.3.2


